# what language the build will be configured for
language: python

# specify what versions of python will be used
# note that all of the versions listed will be tried
python:
    - 3.7

# what branches should be evaluated
branches:
    only:
        - master

# list of commands to run to setup the environment
install:
    - pip install coverage
    - pip install coveralls
    - pip install -r requirements.txt

# the actual commands to run
script:
    # This step installs the package using setup.py
    - python3 setup.py install 
    # This step runs all unit tests and produce test results
    - pytest coronavirus_lifestyle_impacts/tests/
    # This step runs coverage on all the code executed by the main script
    - coverage run coronavirus_lifestyle_impacts/coronavirus_lifestyle_impacts.py
    # This step generates the pylint score for our package
    - pylint coronavirus_lifestyle_impacts

after_success:
    - coverage report
    - coveralls
