# what language the build will be configured for
language: python

# specify what versions of python will be used
# note that all of the versions listed will be tried
python:
    - 3.7

# what branches should be evaluated
branches:
    only:
        - master

# list of commands to run to setup the environment
install:
    - pip install -r requirements.txt


# a list of commands to run before the main script
#before_script:
#    - "flake8 codebase"

# the actual commands to run
script:
    #- coverage run -m unittest discover
    - python3 -c "print('cool')"

#after_success:
#    - coverage report
#    - coveralls
